# quickly setup project with docker
# install docker and docker-compose
# set init.sql in some folder and set up with it by docker
# or import sql
version: "3.8"
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - /usr/local/minio-data:/data
      - /usr/local/minio-config:/root/.minio
    command: server /data --console-address ":9090"
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - /home/mysql/log:/var/log/mysql
      - /home/mysql/data:/var/lib/mysql
      - /home/mysql/conf/my.cnf:/etc/mysql/my.cnf
      # if you want setup with it, free it
      #- ./init.sql:./init.sql
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "boxdb_redis_password_6379"

